apiVersion: core.springclouddataflow.crossplane.io/v1alpha1
kind: Application
metadata:
  name: app-1
spec:
  forProvider:
    name: "App001"
    type: "task"
    version: "3.0.0"
    uri: "docker:springcloudtask/timestamp-task:3.0.0"
    bootVersion: "2"
    defaultVersion: true
  providerConfigRef:
    name: provider-spring-cloud-dataflow-config
---
apiVersion: core.springclouddataflow.crossplane.io/v1alpha1
kind: TaskDefinition
metadata:
  name: task-1
spec:
  forProvider:
    name: "MyTask01"
    description: "Test Task"
    definition: "App001"
  providerConfigRef:
    name: provider-spring-cloud-dataflow-config
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: default
type: Opaque
stringData:
  credentialA: SecretA
  credentialB: SecretB
---
apiVersion: core.springclouddataflow.crossplane.io/v1alpha1
kind: TaskSchedule
metadata:
  name: schedule-1
spec:
  forProvider:
    scheduleName: "myschedule01"
    taskDefinitionNameRef: 
      name: "task-1"
    cronExpression: "* * * * *"
    platform: "default"
    arguments: "--myarg1=value1 --myarg2=value2"
    properties: "scheduler.kubernetes.jobAnnotations=annotation1:value1,annotation2:value2,scheduler.kubernetes.secretRefs=[my-secret]"
  providerConfigRef:
    name: provider-spring-cloud-dataflow-config